return {
    id = "{{PROJECT_ID}}",
    profile = "action-rpg",
    title = "{{PROJECT_TITLE_LUA}}",
    initial_stage = "stage.start",
    fixed_dt = 1 / 60,
    maximum_steps = 8,
    maximum_action_depth = 64,
    content_roots = {"game/content"},
    world = {
        start_time = "08:00",
        seconds_per_day = 0,
    },
    features = {
        "engine.features.accessibility",
        "engine.features.game_flow",
        "engine.features.movement.topdown",
        "engine.features.camera",
        "engine.features.world_state",
        "engine.features.cutscene",
        "engine.features.presentation.impact",
        "engine.features.action.behavior_ai",
        "engine.features.action.hitstop",
        "engine.features.action.knockback",
        "engine.features.action.projectile",
        "engine.features.action.status",
        "engine.features.action.encounter",
        "engine.features.action.dodge",
        "engine.features.action.parry",
        "engine.features.rpg.flags",
        "engine.features.rpg.inventory",
        "engine.features.rpg.equipment",
        "engine.features.rpg.locale",
        "engine.features.rpg.quest",
        "engine.features.rpg.dialogue",
        "engine.features.rpg.shop",
        "engine.features.rpg.interaction",
        "engine.features.rpg.hud",
        "engine.features.presentation.basic",
    },
    locale = {
        default = "locale.en",
    },
    flow = {
        save_slot = "campaign",
        start_stage = "stage.start",
        title = {
            heading = "{{PROJECT_TITLE_LUA}}",
            message = "Accept the guide's request, defeat the enemy, and report back.",
        },
        game_over = {
            heading = "Quest Failed",
            message = "Retry with attacks, projectiles, dodge, and parry.",
        },
        ending = {
            heading = "Quest Complete",
            message = "The enemy is defeated and the reward has been received.",
        },
    },
    input = {
        actions = {
            move_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            move_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            move_left = {keys = {"a", "left"}, buttons = {"dpleft"}},
            move_right = {keys = {"d", "right"}, buttons = {"dpright"}},
            attack = {keys = {"space", "z"}, buttons = {"x"}},
            special = {keys = {"f", "v"}, buttons = {"y"}},
            dodge = {keys = {"lshift", "rshift", "x"}, buttons = {"b"}},
            parry = {keys = {"c", "lctrl", "rctrl"}, buttons = {"leftshoulder"}},
            interact = {keys = {"e"}, buttons = {"x"}},
            menu_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            menu_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            menu_left = {keys = {"a", "left"}, buttons = {"dpleft"}},
            menu_right = {keys = {"d", "right"}, buttons = {"dpright"}},
            menu_confirm = {keys = {"return", "space"}, buttons = {"a"}},
            menu_cancel = {keys = {"escape", "backspace"}, buttons = {"b"}},
            pause = {keys = {"p", "escape"}, buttons = {"start"}},
            restart = {keys = {"r"}, buttons = {"back"}},
            debug_overlay = {keys = {"f1"}, buttons = {}},
        },
    },
}
