return {
    id = "{{PROJECT_ID}}",
    profile = "rpg",
    title = "{{PROJECT_TITLE_LUA}}",
    initial_stage = "stage.start",
    fixed_dt = 1 / 60,
    maximum_steps = 8,
    maximum_action_depth = 64,
    content_roots = {"game/content"},
    world = {
        start_time = "08:00",
        seconds_per_day = 0,
    },
    features = {
        "engine.features.accessibility",
        "engine.features.game_flow",
        "engine.features.movement.topdown",
        "engine.features.camera",
        "engine.features.world_state",
        "engine.features.cutscene",
        "engine.features.action.health",
        "engine.features.rpg.flags",
        "engine.features.rpg.inventory",
        "engine.features.rpg.equipment",
        "engine.features.rpg.locale",
        "engine.features.rpg.quest",
        "engine.features.rpg.turn_battle",
        "engine.features.rpg.dialogue",
        "engine.features.rpg.shop",
        "engine.features.rpg.interaction",
        "engine.features.rpg.hud",
        "engine.features.presentation.basic",
    },
    locale = {
        default = "locale.en",
    },
    flow = {
        save_slot = "campaign",
        start_stage = "stage.start",
        title = {
            heading = "{{PROJECT_TITLE_LUA}}",
            message = "Accept the guide's request and win the turn battle.",
        },
        game_over = {
            heading = "Defeat",
            message = "Recover and challenge the slime again.",
        },
        ending = {
            heading = "Quest Complete",
            message = "The training slime is defeated and the village is safe.",
        },
    },
    input = {
        actions = {
            move_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            move_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            move_left = {keys = {"a", "left"}, buttons = {"dpleft"}},
            move_right = {keys = {"d", "right"}, buttons = {"dpright"}},
            interact = {keys = {"e"}, buttons = {"x"}},
            menu_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            menu_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            menu_left = {keys = {"a", "left"}, buttons = {"dpleft"}},
            menu_right = {keys = {"d", "right"}, buttons = {"dpright"}},
            menu_confirm = {keys = {"return", "space"}, buttons = {"a"}},
            menu_cancel = {keys = {"escape", "backspace"}, buttons = {"b"}},
            pause = {keys = {"p", "escape"}, buttons = {"start"}},
            restart = {keys = {"r"}, buttons = {"back"}},
            debug_overlay = {keys = {"f1"}, buttons = {}},
        },
    },
}
