return {
    id = "{{PROJECT_ID}}",
    profile = "action",
    title = "{{PROJECT_TITLE_LUA}}",
    initial_stage = "stage.start",
    fixed_dt = 1 / 60,
    maximum_steps = 8,
    maximum_action_depth = 64,
    content_roots = {"game/content"},
    features = {
        "engine.features.game_flow",
        "engine.features.movement.topdown",
        "engine.features.camera",
        "engine.features.presentation.impact",
        "engine.features.action.chase_ai",
        "engine.features.action.hitstop",
        "engine.features.action.knockback",
        "engine.features.action.projectile",
        "engine.features.action.status",
        "engine.features.action.encounter",
        "engine.features.action.dodge",
        "engine.features.action.parry",
        "engine.features.presentation.basic",
    },
    flow = {
        save_slot = "campaign",
        start_stage = "stage.start",
    },
    input = {
        actions = {
            move_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            move_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            move_left = {keys = {"a", "left"}, buttons = {"dpleft"}},
            move_right = {keys = {"d", "right"}, buttons = {"dpright"}},
            attack = {keys = {"space", "z"}, buttons = {"x"}},
            special = {keys = {"f", "v"}, buttons = {"y"}},
            dodge = {keys = {"lshift", "rshift", "x"}, buttons = {"b"}},
            parry = {keys = {"c", "lctrl", "rctrl"}, buttons = {"leftshoulder"}},
            menu_up = {keys = {"w", "up"}, buttons = {"dpup"}},
            menu_down = {keys = {"s", "down"}, buttons = {"dpdown"}},
            menu_confirm = {keys = {"return", "space"}, buttons = {"a"}},
            menu_cancel = {keys = {"escape", "backspace"}, buttons = {"b"}},
            pause = {keys = {"p", "escape"}, buttons = {"start"}},
            restart = {keys = {"r"}, buttons = {"back"}},
            debug_overlay = {keys = {"f1"}, buttons = {}},
        },
    },
}
